### ISSUE TITLE
Proposal - revise public API

### ISSUE THREAD

**Issue by iainsmith** [cooklang/CookInSwift#6]
I'd like to propose reworking the public API of the package to make it easier to use in upstream packages. This would be a breaking change:

* Migrate public API types from classes to structs for better local reasoning. (e.g `struct {Recipe,Ingredient,Step}`)
  * Upstream packages can wrap structs in a class where needed and add Idenitifiable conformance.
* Improve some of the names (e.g ParsedEquipment -> Equipment, SemanticRecipe -> Recipe)
* Remove parsing types from the public API (e.g IngredientAmount.value could be a Decimal rather than a ValueNode)
* Provide some convenience methods like `let recipe = try Recipe.from(text: String)`

IMO, this would improve the consumption of the API, but would require changes in the CLI as well. What do you think, is this something you'd be open to changing in the short term, or would you prefer to keep the current API for now?

**Comment by dubadub** [comment]
Hi @iainsmith I certainly agree with all your points and I welcome this change. 

This last layer didn't get much attention. Some other things which should be rethought: `IngredientTable` and `IngredientAmount`. I was considering an option to have them as a type alias for dictionary and have some helpers to merge ingredients from outside (instead of having this inside classes). But struct will work too.

**Comment by dubadub** [comment]
Changes merged to main, thanks @iainsmith for review.
